# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = '''
$hostname$directory$time$git_branch$git_commit$git_state$git_metrics$git_status$conda$character
'''

# Inserts a blank line between shell prompts
add_newline = false

[hostname]
ssh_only = true
style = 'bold green'

[character]
format = ' $symbol '

[directory]
style = "bold cyan"

[git_branch]
format = '[\[$symbol$branch\]]($style)'

[git_commit]
format = '[\[\($hash$tag\)\]]($style)'

[git_metrics]
format = '[\[+$added\]]($added_style)[\[-$deleted\]]($deleted_style)'

[git_state]
format = '[\[$state ($progress_current/$progress_total)\]]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[conda]
format = '[\[ $environment\]]($style)'
style = 'bold blue'
ignore_base = false

[time]
format = '[\[$time\]]($style)'
disabled = false

[localip]
ssh_only = true
disabled = false
format = '@[$localipv4](bold red) '
