# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="zeta"
#ZSH_THEME="spaceship"
#ZSH_THEME="sunaku"
SOLARIZED_THEME="dark"
#ZSH_THEME="jreese"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  tmux
  #command-not-found
  #common-aliases
  #copyfile
  #django
  #extract
  npm
  pip
  python
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

export EDITOR='vim'

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi="vim"
alias jnotebook="jupyter notebook --no-browser --port=8889"

export PATH="$PATH:$HOME/bin"
export PATH=$HOME.local/bin:$PATH

#export LC_ALL=C

export VISUAL=vim
export EDITOR="$VISUAL"

#export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"

#export flags="--config=opt --config=cuda -k"
#alias tmux="TERM=screen-256color-bce tmux"
alias tmux="env TERM=xterm-256color tmux"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'
export LC_CTYPE=en_US.UTF-8


export TVM_HOME=$HOME/Program/incubator-tvm
export PYTHONPATH=$TVM_HOME/python:$TVM_HOME/topi/python:$TVM_HOME/nnvm/python:${PYTHONPATH}
export PATH=$HOME/Program/node/bin:$PATH

export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$HOME/.envs/opt/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$HOME/.envs/opt/lib:$LD_LIBRARY_PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/Program/jdk1.8/bin:$PATH
export PATH=$HOME/Program/gradle-6.1.1/bin:$PATH
export NDK_HOME=$HOME/Program/android-ndk-r20b

export C_INCLUDE_PATH=/usr/local/cuda/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=/usr/local/cuda/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/taco/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/taco/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/pybind11/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/pybind11/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dlpack/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dlpack/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dmlc-core/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dmlc-core/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/rang/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/rang/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/HalideIR/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/HalideIR/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/pytorch/torch/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/pytorch/torch/include:$CPP_INCLUDE_PATH

export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/Program/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/Program/anaconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/Program/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/Program/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

#conda activate janus
conda activate misc

#test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)
export PYTHONPATH=$HOME/Workspace/models:${PYTHONPATH}
