# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

CC=/usr/bin/gcc-8
CXX=/usr/bin/g++-8

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="zeta"
#ZSH_THEME="materialshell"
#ZSH_THEME="spaceship"
#ZSH_THEME="sunaku"
ZSH_THEME="powerlevel10k/powerlevel10k"
SOLARIZED_THEME="dark"
#ZSH_THEME="jreese"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  tmux
  #command-not-found
  #common-aliases
  #copyfile
  #django
  #extract
  npm
  pip
  python
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

export EDITOR='vim'

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi="vim"
alias jnotebook="jupyter notebook --no-browser --port=8889"

export PATH=$HOME/.local/bin:$PATH

#export LC_ALL=C

export VISUAL=vim
export EDITOR="$VISUAL"

if [ -f "$HOME/.local/bin/vim" ]; then
  alias vi="$HOME/.local/bin/vim"
  alias vim="$HOME/.local/bin/vim"
fi

#export flags="--config=opt --config=cuda -k"
#alias tmux="TERM=screen-256color-bce tmux"
alias tmux="env TERM=xterm-256color tmux"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=30'
export LC_CTYPE=en_US.UTF-8

export LLVM_HOME=$HOME/.local/llvm-10.0.0
export PATH=$LLVM_HOME/bin:$PATH
export LIBRARY_PATH=$LLVM_HOME/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$LLVM_HOME/lib:$LD_LIBRARY_PATH
export CPP_INCLUDE_PATH=$LLVM_HOME/include/c++/v1:$CPP_INCLUDE_PATH

#export PATH=$HOME/Program/go/bin:$PATH
#export LIBRARY_PATH=$HOME/Program/go/lib:$LIBRARY_PATH
#export LD_LIBRARY_PATH=$HOME/Program/go/lib:$LD_LIBRARY_PATH

export TVM_HOME=$HOME/Program/incubator-tvm
export PYTHONPATH=$TVM_HOME/python:$TVM_HOME/topi/python:$TVM_HOME/nnvm/python
#export PATH=$HOME/Program/node/bin:$PATH
#export AUTO_HOME=$HOME/Program/FlexTensor
#export PYTHONPATH=$AUTO_HOME:$PYTHONPATH
export PYTHONPATH=$HOME/Workspace/tftachyon

# CUDA related
#export CUDA_HOME=/usr/local/cuda-10.0
export CUDA_HOME=$HOME/.local/cuda-11.0
#export CUDA_HOME=$HOME/.local/cuda-10.2
export TF_CUDA_PATHS=$CUDA_HOME
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=$CUDA_HOME/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/extras/Debugger/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=$CUDA_HOME/extras/Debugger/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=$CUDA_HOME/extras/CUPTI/lib64:$LIBRARY_PATH
export C_INCLUDE_PATH=$CUDA_HOME/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$CUDA_HOME/include:$CPP_INCLUDE_PATH
export C_INCLUDE_PATH=$CUDA_HOME/extras/CUPTI/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$CUDA_HOME/extras/CUPTIinclude:$CPP_INCLUDE_PATH
export C_INCLUDE_PATH=$CUDA_HOME/extras/Debugger/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$CUDA_HOME/extras/Debugger/include:$CPP_INCLUDE_PATH

export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/Program/jdk1.8.0_251/bin:$PATH
export PATH=$HOME/Program/protobuf/bin:$PATH

export ANDROID_SDK_ROOT=$HOME/Android/Sdk
#export ANDROID_NDK_ROOT=$HOME/Android/Ndk
export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
export PATH=$ANDROID_SDK_ROOT/emulator:$PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/pybind11/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/pybind11/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dlpack/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dlpack/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dmlc-core/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/dmlc-core/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/rang/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/rang/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/HalideIR/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/tvm/3rdparty/HalideIR/include:$CPP_INCLUDE_PATH

export C_INCLUDE_PATH=$HOME/Program/pytorch/torch/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/Program/pytorch/torch/include:$CPP_INCLUDE_PATH

export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ktaebum/Program/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ktaebum/Program/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ktaebum/Program/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ktaebum/Program/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export C_INCLUDE_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/include:$C_INCLUDE_PATH
export C_INCLUDE_PATH=/usr/include:$C_INCLUDE_PATH

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
