# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="spaceship"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  tmux
  poetry
  pip
  python
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias tmux="env TERM=xterm-256color tmux"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'
export LANG=en_US.UTF-8

export SSH_KEY_PATH="~/.ssh/rsa_id"

export PERIFLOW_EDITOR=$HOME/.local/nvim/bin/nvim
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/nvim/bin:$PATH
export PATH=$HOME/.local/node/bin:$PATH
export PATH=$HOME/.local/ctags/bin:$PATH
export PATH=$HOME/.local/llvm/bin:$PATH
export PATH=$HOME/.local/gh/bin:$PATH
export PATH=$HOME/.local/protoc/bin:$PATH
export PATH=$HOME/.local/valgrind/bin:$PATH
export PATH=$HOME/.local/cmake/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export LD_LIBRARY_PATH=$HOME/.local/llvm/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$HOME/.local/llvm/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$HOME/.local/llvm/include:$CPP_INCLUDE_PATH

if [ -x "$(command -v nvim)" ]; then
  alias vi="nvim"
  alias vim="nvim"
fi

# CUDA
export CUDA_HOME=/usr/local/cuda
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/extras/Debugger/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$CUDA_HOME/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$CUDA_HOME/include:$CPP_INCLUDE_PATH
export C_INCLUDE_PATH=$CUDA_HOME/extras/Debugger/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$CUDA_HOME/extras/Debugger/include:$CPP_INCLUDE_PATH
export C_INCLUDE_PATH=$CUDA_HOME/extras/CUPTI/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$CUDA_HOME/extras/CUPIT/include:$CPP_INCLUDE_PATH

export VISUAL=nvim
export EDITOR="$VISUAL"

export ORCA_HOME=$HOME/workspace/orca
export HF_HUB_CACHE="/data/huggingface/hub"
export HF_DATASETS_CACHE="/data/huggingface/datasets"

export OPENAI_API_KEY=$(echo -n $(cat $HOME/.local/openai 2>/dev/null))
export FRIENDLI_API_KEY=$(echo -n $(cat $HOME/.local/fai 2>/dev/null))
export ANTHROPIC_API_KEY=$(echo -n $(cat $HOME/.local/anthropic 2>/dev/null))

# SPACESHIP PROMPT
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_ORDER=(
  time
  host
  sudo
  conda
  user
  dir
  git
  char
)
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT='%D{%H:%M:%S}'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$($HOME/program/miniconda3/bin/conda 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/program/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/program/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/program/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
